-- Canciones privadas del Entrenador de canciones (copia personal de práctica).
-- No forman parte del Cancionero Global. Ejecutar en Supabase → SQL Editor.

CREATE TABLE IF NOT EXISTS public.canciones_practica (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid NOT NULL REFERENCES auth.users (id) ON DELETE CASCADE,
  origen_cancion_id bigint REFERENCES public.canciones_guardadas (id) ON DELETE SET NULL,
  nombre text NOT NULL,
  artista text,
  letra text,
  cifrado jsonb,
  compas_config jsonb,
  tonalidad_default smallint,
  modo_tonal_default text NOT NULL DEFAULT 'mayor'
    CHECK (modo_tonal_default IN ('mayor', 'menor')),
  bpm_default smallint,
  tiene_cifrado_avanzado boolean NOT NULL DEFAULT false,
  nota_general text,
  anotaciones jsonb NOT NULL DEFAULT '[]'::jsonb,
  dominio text
    CHECK (dominio IS NULL OR dominio IN ('no_visto', 'practicando', 'dominado')),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS canciones_practica_user_updated_idx
  ON public.canciones_practica (user_id, updated_at DESC);

CREATE INDEX IF NOT EXISTS canciones_practica_origen_idx
  ON public.canciones_practica (user_id, origen_cancion_id)
  WHERE origen_cancion_id IS NOT NULL;

ALTER TABLE public.canciones_practica ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "auth lee canciones practica" ON public.canciones_practica;
CREATE POLICY "auth lee canciones practica"
  ON public.canciones_practica
  FOR SELECT
  TO authenticated
  USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "auth inserta canciones practica" ON public.canciones_practica;
CREATE POLICY "auth inserta canciones practica"
  ON public.canciones_practica
  FOR INSERT
  TO authenticated
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "auth modifica canciones practica" ON public.canciones_practica;
CREATE POLICY "auth modifica canciones practica"
  ON public.canciones_practica
  FOR UPDATE
  TO authenticated
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

DROP POLICY IF EXISTS "auth borra canciones practica" ON public.canciones_practica;
CREATE POLICY "auth borra canciones practica"
  ON public.canciones_practica
  FOR DELETE
  TO authenticated
  USING (auth.uid() = user_id);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.canciones_practica TO authenticated;
GRANT USAGE, SELECT ON SEQUENCE public.canciones_practica_id_seq TO authenticated;

CREATE OR REPLACE FUNCTION public.set_canciones_practica_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_canciones_practica_updated_at ON public.canciones_practica;

CREATE TRIGGER trg_canciones_practica_updated_at
  BEFORE UPDATE ON public.canciones_practica
  FOR EACH ROW
  EXECUTE FUNCTION public.set_canciones_practica_updated_at();
